alias new='acc new --template cpp'
alias sub_old='g++ a.cpp && oj t && acc s'
alias reb='exec $SHELL -l'
alias tmreb='tmux source-file ~/.tmux.conf'
alias pre='python3 ac/ac.py init'
alias sub='python3 ac/ac.py submit'
alias cpy='python3 ac/ac.py copy'
alias clr='python3 ac/ac.py clear'
alias cmp='python3 ac/ac.py compile'
alias run='python3 ac/ac.py run'
alias tpy='python3 ac/ac.py case copy'
alias mksnip='python3 ac/ac.py make-snippets'
alias g='python3 ac/ac.py generate'
alias g2='python3 g/g.py'
alias pc='cd $WREPOS/ac'
alias abca='python3 ac/ac.py abca'

source env.sh
