source_path: "../example.cpp"
formatted_path: "data/tmp/formatted.cpp"
abca_path: "data/tmp/made.cpp"
executable_path: "../a.out"
template_path: "/mnt/c/Users/shktm/AppData/Local/Programs/Python/Python37/Lib/site-packages/atcodertools/tools/templates/tqk.cpp"
template_snippet_path: "data/misc/template.snippet.txt"
snippets_path: "/mnt/c/Users/shktm/source/repos/snippets/library"
library_url: "https://tqkoh.github.io/library/lib"
library_path: "/mnt/c/Users/shktm/source/repos/library"
language_id: 4003
compile: "g++ {{source}} -std=c++1z --exec-charset=cp932 --input-charset=utf-8 -O2 -o ../a.out"
execute: "../a.out"
abca_header: '#include "bits/stdc++.h"\nusing namespace std;\nusing lint = int64_t;\nint main(){\n'
abca_footer: "}"
