name: Test generate
on:
  push:
    branches:
      - 15-feature-test-generate
  pull_request:
    branches:
      - main
jobs:
  test-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Pytest
        run: |
          pytest --durations=0 --capture=no test --junit-xml results/test.xml

      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python 3.10)
          path: results/test.xml
      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
